// Converts an image into ASCII art and overwrites src/ascii.ts with it.
//
//   npx tsx src/generate-ascii.ts <image> [columns]
//
// Dark pixels map to dense characters, so a photo of a dark subject on a
// light background renders the subject and leaves the background empty —
// which works in both the dark and light SVG themes.
import { writeFile } from 'node:fs/promises';
import sharp from 'sharp';
import { artFontSize, artLineHeight, charWidthEm } from './metrics.js';

// A char cell is charW x lineHeight px.
const CHAR_ASPECT = (artFontSize * charWidthEm) / artLineHeight;

// Sparse to dense.
const RAMP = ' .:-=+*#%@';

const [imagePath, columnsArg] = process.argv.slice(2);
if (!imagePath) {
	console.error('Usage: npx tsx src/generate-ascii.ts <image> [columns]');
	process.exit(1);
}
const columns = Number(columnsArg ?? 64);

const metadata = await sharp(imagePath).metadata();
if (!metadata.width || !metadata.height) {
	throw new Error(`Could not read dimensions of ${imagePath}`);
}
const rows = Math.round(columns * (metadata.height / metadata.width) * CHAR_ASPECT);

const data = await sharp(imagePath)
	.resize(columns, rows, { fit: 'fill' })
	.grayscale()
	.normalise()
	.raw()
	.toBuffer();

const lines: string[] = [];
for (let y = 0; y < rows; y++) {
	let line = '';
	for (let x = 0; x < columns; x++) {
		const darkness = 1 - data[y * columns + x] / 255;
		line += RAMP[Math.min(RAMP.length - 1, Math.floor(darkness * RAMP.length))];
	}
	lines.push(line.trimEnd());
}

const file = `// AUTO-GENERATED by src/generate-ascii.ts — regenerate instead of editing:
//   npx tsx src/generate-ascii.ts <image> [columns]
// Aspect ratio is baked from src/metrics.ts.
export const asciiArt = ${JSON.stringify(lines, null, '\t')};
`;

await writeFile(new URL('./ascii.ts', import.meta.url), file);
console.log(`Wrote ${rows}x${columns} ASCII art to src/ascii.ts`);
